name: Pipeline para Aprender CI/CD
on:
    push:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Setup Python
              uses: actions/setup-python@v5
              with:
                python-version: 3.8
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt
            - name: Run tests
              run: |
                python -m pytest tests/
    deploy:
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name: Deploy to Python Anywhere
              uses: jensvog/pythonanywhere-webapp-reload-action@v1
              with:
                host: 'fabriciobizotto.pythonanywhere.com'
                username: ${{ secrets.API_USERNAME }}
                api-token: ${{ secrets.API_KEY }}
                domain-name: ${{ secrets.API_DOMAIN_NAME }}