name: Pipeline para Aprender CI/CD
on:
    push:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-python@v5
              with:
                python-version: 3.8
            - run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt
